=== Dannyps/laig1/scenes/yas.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT yas (scene,views,ambient,lights,textures,materials,
               transformations,primitives,components)>
<!ATTLIST yas
  xmlns CDATA #FIXED ''>

<!ELEMENT scene EMPTY>
<!ATTLIST scene
  xmlns CDATA #FIXED ''
  axis_length CDATA #REQUIRED
  root NMTOKEN #REQUIRED>

<!ELEMENT views (perspective,ortho)>
<!ATTLIST views
  xmlns CDATA #FIXED ''
  default NMTOKEN #REQUIRED>

<!ELEMENT lights (omni,spot)>
<!ATTLIST lights
  xmlns CDATA #FIXED ''>

<!ELEMENT textures (texture)>
<!ATTLIST textures
  xmlns CDATA #FIXED ''>

<!ELEMENT transformations (transformation)>
<!ATTLIST transformations
  xmlns CDATA #FIXED ''>

<!ELEMENT primitives (primitive)>
<!ATTLIST primitives
  xmlns CDATA #FIXED ''>

<!ELEMENT components (component)>
<!ATTLIST components
  xmlns CDATA #FIXED ''>

<!ELEMENT perspective (from,to)>
<!ATTLIST perspective
  xmlns CDATA #FIXED ''
  angle NMTOKEN #REQUIRED
  far NMTOKEN #REQUIRED
  id NMTOKEN #REQUIRED
  near NMTOKEN #REQUIRED>

<!ELEMENT ortho EMPTY>
<!ATTLIST ortho
  xmlns CDATA #FIXED ''
  bottom NMTOKEN #REQUIRED
  far NMTOKEN #REQUIRED
  id NMTOKEN #REQUIRED
  left NMTOKEN #REQUIRED
  near NMTOKEN #REQUIRED
  right NMTOKEN #REQUIRED
  top NMTOKEN #REQUIRED>

<!ELEMENT omni (location,ambient,diffuse,specular)>
<!ATTLIST omni
  xmlns CDATA #FIXED ''
  enabled NMTOKEN #REQUIRED
  id NMTOKEN #REQUIRED>

<!ELEMENT spot (location,target,ambient,diffuse,specular)>
<!ATTLIST spot
  xmlns CDATA #FIXED ''
  angle NMTOKEN #REQUIRED
  enabled NMTOKEN #REQUIRED
  exponent NMTOKEN #REQUIRED
  id NMTOKEN #REQUIRED>

<!ELEMENT primitive (rectangle,triangle,cylinder,sphere,torus)>
<!ATTLIST primitive
  xmlns CDATA #FIXED ''
  id NMTOKEN #REQUIRED>

<!ELEMENT component (transformation,materials,texture,children)>
<!ATTLIST component
  xmlns CDATA #FIXED ''
  id NMTOKEN #REQUIRED>

<!ELEMENT from EMPTY>
<!ATTLIST from
  xmlns CDATA #FIXED ''
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  z NMTOKEN #REQUIRED>

<!ELEMENT to EMPTY>
<!ATTLIST to
  xmlns CDATA #FIXED ''
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  z NMTOKEN #REQUIRED>

<!ELEMENT target EMPTY>
<!ATTLIST target
  xmlns CDATA #FIXED ''
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  z NMTOKEN #REQUIRED>

<!ELEMENT rectangle EMPTY>
<!ATTLIST rectangle
  xmlns CDATA #FIXED ''
  x1 NMTOKEN #REQUIRED
  x2 NMTOKEN #REQUIRED
  y1 NMTOKEN #REQUIRED
  y2 NMTOKEN #REQUIRED>

<!ELEMENT triangle EMPTY>
<!ATTLIST triangle
  xmlns CDATA #FIXED ''
  x1 NMTOKEN #REQUIRED
  x2 NMTOKEN #REQUIRED
  x3 NMTOKEN #REQUIRED
  y1 NMTOKEN #REQUIRED
  y2 NMTOKEN #REQUIRED
  y3 NMTOKEN #REQUIRED
  z1 NMTOKEN #REQUIRED
  z2 NMTOKEN #REQUIRED
  z3 NMTOKEN #REQUIRED>

<!ELEMENT cylinder EMPTY>
<!ATTLIST cylinder
  xmlns CDATA #FIXED ''
  base NMTOKEN #REQUIRED
  height NMTOKEN #REQUIRED
  slices NMTOKEN #REQUIRED
  stacks NMTOKEN #REQUIRED
  top NMTOKEN #REQUIRED>

<!ELEMENT sphere EMPTY>
<!ATTLIST sphere
  xmlns CDATA #FIXED ''
  radius NMTOKEN #REQUIRED
  slices NMTOKEN #REQUIRED
  stacks NMTOKEN #REQUIRED>

<!ELEMENT torus EMPTY>
<!ATTLIST torus
  xmlns CDATA #FIXED ''
  inner NMTOKEN #REQUIRED
  loops NMTOKEN #REQUIRED
  outer NMTOKEN #REQUIRED
  slices NMTOKEN #REQUIRED>

<!ELEMENT children (componentref,primitiveref)>
<!ATTLIST children
  xmlns CDATA #FIXED ''>

<!ELEMENT componentref EMPTY>
<!ATTLIST componentref
  xmlns CDATA #FIXED ''
  id NMTOKEN #REQUIRED>

<!ELEMENT primitiveref EMPTY>
<!ATTLIST primitiveref
  xmlns CDATA #FIXED ''
  id NMTOKEN #REQUIRED>

<!ELEMENT ambient (ambient|background)?>
<!ATTLIST ambient
  xmlns CDATA #FIXED ''
  a NMTOKEN #IMPLIED
  b NMTOKEN #IMPLIED
  g NMTOKEN #IMPLIED
  r NMTOKEN #IMPLIED>

<!ELEMENT background EMPTY>
<!ATTLIST background
  xmlns CDATA #FIXED ''
  a NMTOKEN #REQUIRED
  b NMTOKEN #REQUIRED
  g NMTOKEN #REQUIRED
  r NMTOKEN #REQUIRED>

<!ELEMENT location EMPTY>
<!ATTLIST location
  xmlns CDATA #FIXED ''
  w NMTOKEN #REQUIRED
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  z NMTOKEN #REQUIRED>

<!ELEMENT diffuse EMPTY>
<!ATTLIST diffuse
  xmlns CDATA #FIXED ''
  a NMTOKEN #REQUIRED
  b NMTOKEN #REQUIRED
  g NMTOKEN #REQUIRED
  r NMTOKEN #REQUIRED>

<!ELEMENT specular EMPTY>
<!ATTLIST specular
  xmlns CDATA #FIXED ''
  a NMTOKEN #REQUIRED
  b NMTOKEN #REQUIRED
  g NMTOKEN #REQUIRED
  r NMTOKEN #REQUIRED>

<!ELEMENT texture EMPTY>
<!ATTLIST texture
  xmlns CDATA #FIXED ''
  file NMTOKEN #IMPLIED
  id NMTOKEN #REQUIRED
  length_s NMTOKEN #IMPLIED
  length_t NMTOKEN #IMPLIED>

<!ELEMENT materials (material)>
<!ATTLIST materials
  xmlns CDATA #FIXED ''>

<!ELEMENT material (emission,ambient,diffuse,specular)?>
<!ATTLIST material
  xmlns CDATA #FIXED ''
  id NMTOKEN #REQUIRED
  shininess NMTOKEN #IMPLIED>

<!ELEMENT emission EMPTY>
<!ATTLIST emission
  xmlns CDATA #FIXED ''
  a NMTOKEN #REQUIRED
  b NMTOKEN #REQUIRED
  g NMTOKEN #REQUIRED
  r NMTOKEN #REQUIRED>

<!ELEMENT transformation (transformationref?,translate,rotate,scale)>
<!ATTLIST transformation
  xmlns CDATA #FIXED ''
  id NMTOKEN #IMPLIED>

<!ELEMENT transformationref EMPTY>
<!ATTLIST transformationref
  xmlns CDATA #FIXED ''
  id NMTOKEN #REQUIRED>

<!ELEMENT translate EMPTY>
<!ATTLIST translate
  xmlns CDATA #FIXED ''
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  z NMTOKEN #REQUIRED>

<!ELEMENT rotate EMPTY>
<!ATTLIST rotate
  xmlns CDATA #FIXED ''
  angle NMTOKEN #REQUIRED
  axis NMTOKEN #REQUIRED>

<!ELEMENT scale EMPTY>
<!ATTLIST scale
  xmlns CDATA #FIXED ''
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  z NMTOKEN #REQUIRED>

=== Dannyps/laig1/scenes/example-yas.xml
<!DOCTYPE yas SYSTEM "yas.dtd">
<!-- Os comentarios devem ter espacos no inicio e no fim, a -->
<!-- separar dos hifens -->
<!-- Nao devem ser usados caracteres especiais (p.ex. acentos) -->
<!-- Todas as tags e atributos sao obrigatorios, exceto onde for -->
<!-- referido o contrario -->
<!-- Na descricao abaixo, os simbolos utilizados tem o seguinte significado: -->
<!-- ii: integer value -->
<!-- ff: float value -->
<!-- ss: string value -->
<!-- cc: character "x" or "y" or "z" -->
<!-- tt: "0" or "1" with Boolean significance -->
<yas>
    <!-- deve definir-se um objeto para raiz da arvore, assim -->
    <!-- como o comprimento dos tres eixos (cilindros) -->
    <scene root="cc1" axis_length="5.0" />
    <views default="vp1">
        <!-- tem de existir, pelo menos, uma vista de -->
        <!-- entre as seguintes (perspective ou ortho) -->
        <perspective id="vp1" near="0.1" far="500" angle="0.4">
            <from x="15" y="15" z="15" />
            <to x="0" y="0" z="0" />
        </perspective>
        <ortho id="vo1" near="ff" far="ff" left="ff" right="ff" top="ff" bottom="ff" />
    </views>
    <ambient>
        <ambient r="0.5" g="0.5" b="0.5" a="1" />
        <background r="0.5" g="0" b="0" a="1" />
    </ambient>
    <lights>
        <!-- Deve existir um ou mais blocos "omni" ou "spot" -->
        <!-- Os identificadores "id" nao podem ser repetidos -->
        <omni id="lo1" enabled="true">
            <location x="5" y="10" z="5" w="1" />
            <ambient r="0" g="0" b="0" a="0" />
            <diffuse r="0.5" g="0" b="0.3" a="1" />
            <specular r="0.2" g="0" b="0.1" a="1" />
        </omni>
        <!--<omni id="lo2" enabled="true">
            <location x="5" y="5" z="5" w="0" />
            <ambient r="0" g="1" b="0" a="1" />
            <diffuse r="0" g="0.2" b="0" a="1" />
            <specular r="0" g="0" b="0" a="1" />
        </omni>-->
        <spot id="ls1" enabled="true" angle="0.5" exponent="2">
            <!-- atencao, "target" e' diferente de "direction" -->
            <location x="0" y="2" z="5" w="1" />
            <target x="0" y="0" z="0" />
            <ambient r="0" g="0" b="0" a="0" />
            <diffuse r="0" g="0.5" b="0.5" a="1" />
            <specular r="0" g="0" b="0" a="1" />
        </spot>
    </lights>
    <textures>
        <!-- Deve existir um ou mais blocos "texture" -->
        <!-- Os identificadores "id" nao podem ser repetidos -->
        <texture id="tt1" file="ss" />
        <texture id="tt2" file="sds" />
    </textures>
    <materials>
        <!-- Deve existir um ou mais blocos "material" -->
        <!-- Os identificadores "id" nao podem ser repetidos -->
        <material id="mm1" shininess = "1">
            <emission r="0" g="0" b="0" a="0" />
            <ambient r="0.2" g="0.2" b="0.2" a="1" />
            <diffuse r="0.3" g="0.3" b="0.3" a="1" />
            <specular r="0" g="0" b="0" a="1" />
        </material>

        <material id="greenLight">
            <ambient r="0" g="1" b="0" a="1" />
        </material>
        <material id="yellowLight">
            <ambient r="1" g="1" b="0" a="1" />
        </material>
        <material id="redLight">
            <ambient r="1" g="0" b="0" a="1" />
        </material>
        <material id="semaphore">
            <ambient r="0.4" g="0.4" b="0.4" a="1" /> <!-- dim grey -->
        </material>
    </materials>
    <transformations>
        <!-- Deve existir um ou mais blocos "transformation" -->
        <!-- Os identificadores "id" nao podem ser repetidos -->
        <!-- Os angulos sao expressos em graus -->
        <transformation id="tt1">
            <!-- instrucoes a usar sem limite nem ordem -->
            <!-- deve existir pelo menos uma transformacao -->
            <translate x="2" y="0" z="0" />
            <rotate axis="z" angle="180" />
            <scale x="1" y="2" z="1" />
        </transformation>
    </transformations>
    <primitives>
        <!-- Uma "primitive" e' uma primitiva e pode ser usada em nos folha -->
        <!-- Deve existir um ou mais blocos "primitive" -->
        <!-- Os identificadores "id" nao podem ser repetidos -->
        <primitive id="pRect">
            <!-- apenas pode existir UMA das seguintes tags: -->
            <!-- rectangle, triangle, cylinder, sphere, torus -->
            <!-- os parametros devem ser interpretados, genericamente, -->
            <!-- como em WebGL; o cilindro deve adicionalmente ter tampas -->
            <rectangle x1="-0.5" y1="-0.5" x2="0.5" y2="0.5" />
        </primitive >

        <primitive id="pTriang">
            <triangle x1="-0.5" y1="-0.5" z1="-0.5" x2="-0.5" y2="-0.5" z2="0.5" x3="0.5" y3="-0.5" z3="-0.5" />
        </primitive>

        <primitive id="pCylind">
            <cylinder base="1" top="1" height="1" slices="10" stacks="20" />
        </primitive>

        <primitive id="pSphere">
            <sphere radius="1" slices="20" stacks="20" />
        </primitive>

        <primitive id="pTorus">
            <torus inner="ff" outer="ff" slices="ii" loops="ii" />
        </primitive>

    </primitives >
    <components>
        <component id="cubeFrontFace">
            <transformation>
                <translate x="0" y="0" z="0.5"/>
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <primitiveref id="pQuad"/>
            </children>
        </component>

        <component id="cubeBackFace">
            <transformation>
                <rotate axis="y" angle="180"/>
                <translate x="0" y="0" z="0.5"/>
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <primitiveref id="pQuad"/>
            </children>
        </component>

        <component id="cubeRightFace">
            <transformation>
                <rotate axis="y" angle="90"/>
                <translate x="0" y="0" z="0.5"/>
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <primitiveref id="pQuad"/>
            </children>
        </component>

        <component id="cubeLeftFace">
            <transformation>
                <rotate axis="y" angle="-90"/>
                <translate x="0" y="0" z="0.5"/>
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <primitiveref id="pQuad"/>
            </children>
        </component>

        <component id="cubeTopFace">
            <transformation>
                <rotate axis="x" angle="-90"/>
                <translate x="0" y="0" z="0.5"/>
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <primitiveref id="pQuad"/>
            </children>
        </component>

        <component id="cubeBottomFace">
            <transformation>
                <rotate axis="x" angle="90"/>
                <translate x="0" y="0" z="0.5"/>
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <primitiveref id="pQuad"/>
            </children>
        </component>

        <component id="cube">
            <transformation>
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <componentref id="cubeFrontFace"/>
                <componentref id="cubeBackFace"/>
                <componentref id="cubeLeftFace"/>
                <componentref id="cubeRightFace"/>
                <componentref id="cubeTopFace"/>
                <componentref id="cubeBottomFace"/>
            </children>
        </component>

        <component id="semBase">
            <transformation>
                <translate x="0" y="0.5" z="0">
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <componentref id="cube"/>
            </children>
        </component>

        <component id="semPoste">
            <transformation>
                <scale x="0.2" y="4" z="0.2">
                <translate x="0" y="4.5" z="0">
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <componentref id="cube"/>
            </children>
        </component>
        
        <component id="semHead">
            <transformation>
                <translate x="0" y="5" z="0">
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
            <texture id="inherit" length_s="1" length_t="1" />
            <children>
                <componentref id="cube"/>
            </children>
        </component>                
        
        <component id="semaforo">
            <transformation>
            </transformation>
            <materials>
                <materialref id="inherit" />
            </materials>
